# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.4

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/paarth/An open source browser"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/paarth/An open source browser/build"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/paarth/An open source browser/build/CMakeFiles" "/Users/paarth/An open source browser/build//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/paarth/An open source browser/build/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named gecko_browser

# Build rule for target.
gecko_browser: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 gecko_browser
.PHONY : gecko_browser

# fast build rule for target.
gecko_browser/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/build
.PHONY : gecko_browser/fast

src/browser_app.o: src/browser_app.cpp.o
.PHONY : src/browser_app.o

# target to build an object file
src/browser_app.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/browser_app.cpp.o
.PHONY : src/browser_app.cpp.o

src/browser_app.i: src/browser_app.cpp.i
.PHONY : src/browser_app.i

# target to preprocess a source file
src/browser_app.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/browser_app.cpp.i
.PHONY : src/browser_app.cpp.i

src/browser_app.s: src/browser_app.cpp.s
.PHONY : src/browser_app.s

# target to generate assembly for a file
src/browser_app.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/browser_app.cpp.s
.PHONY : src/browser_app.cpp.s

src/gecko_bridge.o: src/gecko_bridge.cpp.o
.PHONY : src/gecko_bridge.o

# target to build an object file
src/gecko_bridge.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/gecko_bridge.cpp.o
.PHONY : src/gecko_bridge.cpp.o

src/gecko_bridge.i: src/gecko_bridge.cpp.i
.PHONY : src/gecko_bridge.i

# target to preprocess a source file
src/gecko_bridge.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/gecko_bridge.cpp.i
.PHONY : src/gecko_bridge.cpp.i

src/gecko_bridge.s: src/gecko_bridge.cpp.s
.PHONY : src/gecko_bridge.s

# target to generate assembly for a file
src/gecko_bridge.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/gecko_bridge.cpp.s
.PHONY : src/gecko_bridge.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/gecko_browser.dir/build.make CMakeFiles/gecko_browser.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... gecko_browser"
	@echo "... src/browser_app.o"
	@echo "... src/browser_app.i"
	@echo "... src/browser_app.s"
	@echo "... src/gecko_bridge.o"
	@echo "... src/gecko_bridge.i"
	@echo "... src/gecko_bridge.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

